# Minimal HPC-ready Makefile for TSP-GA-CUDA
# Builds the retained CUDA binaries into build/

CC ?= gcc
NVCC ?= nvcc

CUDA_HOME ?=
ifeq ($(strip $(CUDA_HOME)),)
  NVCC_CMD := $(NVCC)
else
  NVCC_CMD := $(CUDA_HOME)/bin/$(NVCC)
endif

BUILD_DIR := build

SBATCH ?= sbatch
CUDA_MATRIX_RUNS ?= 20
CUDA_MATRIX_ISLANDS ?= 256
CUDA_MATRIX_GENERATIONS ?= 2000
CUDA_MATRIX_MUTATION ?= 0.03
CUDA_MATRIX_ELITE_POP ?= 2
CUDA_MATRIX_SEED_BASE ?= 100
CUDA_MATRIX_BERLIN_DATASET ?= data/berlin52.tsp

NAIVE_SRC := src/cuda/GPU-Naive.cu
ISLAND_SRC := src/cuda/CUDA-GA-GPU-Pop.cu
ISLAND_BANKCONFLICT_SRC := src/cuda/variants/CUDA-GA-GPU-Pop-bankconflict.cu
ISLAND_BITSET_SRC := src/cuda/variants/CUDA-GA-GPU-Pop-bitset.cu
ISLAND_PARALLEL_SORT_SRC := src/cuda/variants/CUDA-GA-GPU-Pop-ParallelSort.cu
ISLAND_AOS_SRC := src/cuda/variants/CUDA-GA-GPU-Pop-AoS.cu
ISLAND_GLOBAL_DIST_SRC := src/cuda/variants/CUDA-GA-GPU-Pop-GlobalDist.cu
PARSER_SRC := src/cpp/tsplib_parser.cpp
PARSER_HDR := src/cpp/tsplib_parser.h

NAIVE_BIN := $(BUILD_DIR)/GPU-Naive
ISLAND_BIN := $(BUILD_DIR)/CUDA-GA-GPU-Pop
ISLAND_BANKCONFLICT_BIN := $(BUILD_DIR)/CUDA-GA-GPU-Pop-bankconflict
ISLAND_BITSET_BIN := $(BUILD_DIR)/CUDA-GA-GPU-Pop-bitset
ISLAND_PARALLEL_SORT_BIN := $(BUILD_DIR)/GA-GPU-POP-ParallelSort
ISLAND_AOS_BIN := $(BUILD_DIR)/GA-GPU-POP-AoS
ISLAND_GLOBAL_DIST_BIN := $(BUILD_DIR)/GA-GPU-POP-GlobalDist

CUDA_BINS := \
	$(NAIVE_BIN) \
	$(ISLAND_BIN) \
	$(ISLAND_BANKCONFLICT_BIN) \
	$(ISLAND_BITSET_BIN) \
	$(ISLAND_PARALLEL_SORT_BIN) \
	$(ISLAND_AOS_BIN) \
	$(ISLAND_GLOBAL_DIST_BIN)

NVCCFLAGS ?= -O3 -std=c++11 -Xcompiler -std=gnu++11 -arch=sm_60 -lineinfo -Isrc/cpp

.PHONY: all all_cuda_versions clean dirs info sbatch_cuda_berlin52 print_cuda_matrix_config

all: all_cuda_versions

all_cuda_versions: dirs $(CUDA_BINS)

dirs:
	mkdir -p $(BUILD_DIR)

info:
	@echo "CC=$(CC)"
	@echo "NVCC=$(NVCC_CMD)"
	@echo "CUDA_HOME=$(CUDA_HOME)"
	@echo "BUILD_DIR=$(BUILD_DIR)"
	@echo "NAIVE_SRC=$(NAIVE_SRC)"
	@echo "ISLAND_SRC=$(ISLAND_SRC)"
	@echo "ISLAND_BANKCONFLICT_SRC=$(ISLAND_BANKCONFLICT_SRC)"
	@echo "ISLAND_BITSET_SRC=$(ISLAND_BITSET_SRC)"
	@echo "ISLAND_PARALLEL_SORT_SRC=$(ISLAND_PARALLEL_SORT_SRC)"
	@echo "ISLAND_AOS_SRC=$(ISLAND_AOS_SRC)"
	@echo "ISLAND_GLOBAL_DIST_SRC=$(ISLAND_GLOBAL_DIST_SRC)"
	@echo "PARSER_SRC=$(PARSER_SRC)"

print_cuda_matrix_config:
	@echo "RUNS=$(CUDA_MATRIX_RUNS)"
	@echo "ISLANDS=$(CUDA_MATRIX_ISLANDS)"
	@echo "GENERATIONS=$(CUDA_MATRIX_GENERATIONS)"
	@echo "MUTATION=$(CUDA_MATRIX_MUTATION)"
	@echo "ELITE_POP=$(CUDA_MATRIX_ELITE_POP)"
	@echo "SEED_BASE=$(CUDA_MATRIX_SEED_BASE)"
	@echo "BERLIN_DATASET=$(CUDA_MATRIX_BERLIN_DATASET)"

sbatch_cuda_berlin52:
	$(SBATCH) --export=ALL,DATASET=$(CUDA_MATRIX_BERLIN_DATASET),RUNS=$(CUDA_MATRIX_RUNS),ISLANDS=$(CUDA_MATRIX_ISLANDS),GENERATIONS=$(CUDA_MATRIX_GENERATIONS),MUTATION=$(CUDA_MATRIX_MUTATION),ELITE_POP=$(CUDA_MATRIX_ELITE_POP),SEED_BASE=$(CUDA_MATRIX_SEED_BASE) slurm/run_cuda_all_variants_csv.slurm

$(NAIVE_BIN): $(NAIVE_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(NAIVE_SRC) $(PARSER_SRC)

$(ISLAND_BIN): $(ISLAND_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_SRC) $(PARSER_SRC)

$(ISLAND_BANKCONFLICT_BIN): $(ISLAND_BANKCONFLICT_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_BANKCONFLICT_SRC) $(PARSER_SRC)

$(ISLAND_BITSET_BIN): $(ISLAND_BITSET_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_BITSET_SRC) $(PARSER_SRC)

$(ISLAND_PARALLEL_SORT_BIN): $(ISLAND_PARALLEL_SORT_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_PARALLEL_SORT_SRC) $(PARSER_SRC)

$(ISLAND_AOS_BIN): $(ISLAND_AOS_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_AOS_SRC) $(PARSER_SRC)

$(ISLAND_GLOBAL_DIST_BIN): $(ISLAND_GLOBAL_DIST_SRC) $(PARSER_SRC) $(PARSER_HDR)
	$(NVCC_CMD) $(NVCCFLAGS) -o $@ $(ISLAND_GLOBAL_DIST_SRC) $(PARSER_SRC)

clean:
	rm -rf $(BUILD_DIR)
